buildscript {
    repositories { google() }
    dependencies { classpath 'com.android.tools.build:gradle:8.2.2' }
}

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '1.9.22'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.baz.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.baz.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.22'
}
